### ISSUE TITLE
Issue with TimeDistributedConvolution2D 

### ISSUE THREAD

**Issue by littonj97** [anayebi/keras-extra#14]
n_hidden = 256
n_samples = 100
n_timesteps = 16

model = Sequential()
model.add(TimeDistributedConvolution2D(32, 5, 5, border_mode='same', input_shape=(n_timesteps, 28, 28)))
model.add(TimeDistributedMaxPooling2D(pool_size=(nb_pool, nb_pool)))
model.add(Activation('relu'))
model.add(TimeDistributedFlatten())
model.add(LSTM(256, return_sequences=True))
model.add(TimeDistributedDense(nb_classes))
model.add(Activation('softmax')) 

the above code throws error as http://pastebin.com/E319wGeg

**Comment by oakkas** [comment]
I am getting the following error when I also run the baove code:
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 1556, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 940, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/oakkas/Desktop/autocar/handStateModel2.py", line 47, in <module>
    model.add(extra.TimeDistributedConvolution2D(32, 5, 5, border_mode='same', input_shape=(None, n_timesteps, 3, 256, 256)))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/extra.py", line 89, in **init**
    self.input = K.placeholder(ndim=5)
AttributeError: can't set attribute

**Comment by amir-abdi** [comment]
Same error here

**Comment by a00achild1** [comment]
I have the same error.
Is this the version problem?

**Comment by amir-abdi** [comment]
My problem solved as I figured that keras already has TimeDistributed layers and we don't need these extra layers anymore.

**Comment by a00achild1** [comment]
@amir-abdi thanks for your information, I'll give it a try!
